### PR TITLE
Information improvement

### PR DESCRIPTION
**Pull request by jundurraga**
Hi Mickstar, 
I modified the item text to show the year and journal-title. I find this useful when exploring papers. Please check this out and see if you find it useful. 
It seems that Zotero does not export dates in a standard way, and this may require some extra tweaks to sort by date properly.
Cheers
Jaime
Screenshot_1597118270

### CODE REVIEW

**Comment by jundurraga** [comment]
yep, it depends on the length of the entire string. perhps that can be limited to prevent that?

**Comment by jundurraga** [comment]
Actually it looks quite nice in the tablet, so perhaps the length may depend on the device screen size.

**Comment by jundurraga** [comment]
Screenshot from 2020-08-11 17-33-07

**Comment by mickstar** [comment]
Thanks a lot, I will merge and submit it on the weekend

**Comment by mickstar** [comment]
noticed that it crashes on android 5.0 (API 21)
appears that DateTimeFormatter is not available. I will need to fix this before it goes live

**Comment by mickstar** [comment]
fixed here 6d04834e4e5362d64e4891e9c8777fd9a2992599

**Pull request merged**
